/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gaming_chair.glb 
Author: snjvsngh_negi (https://sketchfab.com/snjvsngh_negi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-chair-601afdea98f14c488ee0be0ffb4b92dd
Title: Gaming chair
*/

import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { useGLTF } from '@react-three/drei'
import { forwardRef } from "react";
import  {ThreeElements}  from "@react-three/fiber";

type GroupProps = ThreeElements["group"];

type GLTFResult = GLTF & {
  nodes: {
    adjustment_aiStandardSurface1_0: THREE.Mesh;
    pCube6_aiStandardSurface1_0: THREE.Mesh;
    pCube9_aiStandardSurface1_0: THREE.Mesh;
    pPlane3_aiStandardSurface1_0: THREE.Mesh;
    pCylinder14_aiStandardSurface1_0: THREE.Mesh;
    pCylinder10_aiStandardSurface1_0: THREE.Mesh;
    Bolt_aiStandardSurface1_0: THREE.Mesh;
    Bolt1_aiStandardSurface1_0: THREE.Mesh;
    Bolt2_aiStandardSurface1_0: THREE.Mesh;
    Bolt3_aiStandardSurface1_0: THREE.Mesh;
    polySurface11_aiStandardSurface1_0: THREE.Mesh;
    wheel_aiStandardSurface1_0: THREE.Mesh;
    wheel2_aiStandardSurface1_0: THREE.Mesh;
    wheel3_aiStandardSurface1_0: THREE.Mesh;
    wheel4_aiStandardSurface1_0: THREE.Mesh;
    polySurface24_aiStandardSurface1_0: THREE.Mesh;
    polySurface43_aiStandardSurface1_0: THREE.Mesh;
    back_bone_aiStandardSurface1_0: THREE.Mesh;
    butt_aiStandardSurface1_0: THREE.Mesh;
    L_handle_aiStandardSurface1_0: THREE.Mesh;
    R_handle_aiStandardSurface1_0: THREE.Mesh;
    back2_aiStandardSurface1_0: THREE.Mesh;
  };
  materials: {
    aiStandardSurface1: THREE.MeshStandardMaterial;
  };
};

export const GamingChair = forwardRef<THREE.Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF('/models/gaming_chair.glb');
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.adjustment_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
      <mesh geometry={nodes.pCube6_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} position={[1.12, -9.447, 1.613]} rotation={[0.779, -0.038, 2.354]} scale={[0.033, 1.248, 0.737]} />
      <mesh geometry={nodes.pCube9_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
      <mesh geometry={nodes.pPlane3_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
      <mesh geometry={nodes.pCylinder14_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} position={[-0.723, -0.428, -2.004]} rotation={[-0.172, 0, 0]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.pCylinder10_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} position={[-0.437, -9.59, 1.608]} rotation={[-0.168, 0, 0]} scale={0.655} />
      <mesh geometry={nodes.Bolt_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} position={[-1.698, -9.014, -0.193]} rotation={[0, 0, Math.PI / 2]} scale={[0.186, 0.051, 0.186]} />
      <mesh geometry={nodes.Bolt1_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} position={[-1.378, -9.262, -1.907]} rotation={[0, 0, 1.443]} scale={[0.119, 0.065, 0.119]} />
      <mesh geometry={nodes.Bolt2_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} position={[0.625, -9.262, -1.907]} rotation={[0, 0, 1.685]} scale={[0.119, 0.065, 0.119]} />
      <mesh geometry={nodes.Bolt3_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} position={[0.971, -9.014, -0.193]} rotation={[0, 0, Math.PI / 2]} scale={[0.186, 0.051, 0.186]} />
      <mesh geometry={nodes.polySurface11_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} position={[-0.185, 0.079, 0.355]} scale={[1.959, 1, 1]} />
      <mesh geometry={nodes.wheel_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
      <mesh geometry={nodes.wheel2_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} position={[0.317, 0, -1.275]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.wheel3_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} position={[-1.275, 0, -0.317]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.wheel4_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} position={[-0.958, 0, -1.591]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.polySurface24_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
      <mesh geometry={nodes.polySurface43_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
      <mesh geometry={nodes.back_bone_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
      <mesh geometry={nodes.butt_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
      <mesh geometry={nodes.L_handle_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
      <mesh geometry={nodes.R_handle_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} position={[-0.756, 0, 0]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.back2_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
    </group>
  )
}
);

useGLTF.preload('/models/gaming_chair.glb');
